### ISSUE TITLE
vk_music

### ISSUE THREAD

**Issue by stleon** [demidovakatya/vk-playlist#1]
https://github.com/stleon/vk_music

есть еще

https://github.com/genaev/vmd

**Comment by demidovakatya** [comment]
спасибо! :sunny: 

твоя реализация – самая крутая из всех, что я видела (отдельное «ура» третьему питону).

**Comment by stleon** [comment]
Спасибо, но она далеко не идеальная)

**Comment by demidovakatya** [comment]
по крайней мере, предпочту учиться на ней, нежели на [этом крике души](https://habrahabr.ru/post/143860/)

**Comment by demidovakatya** [comment]
:heavy_check_mark:
